// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"whispering-pines/pkg/meta"
	"whispering-pines/pkg/templates/layouts"
)

func Clubhouse() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = PageHero("Clubhouse", "Your home on the course").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <section class=\"py-12 sm:py-24 bg-white\"><div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8\"><!-- Featured Images Grid --><div class=\"grid md:grid-cols-2 gap-4 mb-12\"><div class=\"rounded-2xl overflow-hidden shadow-lg\"><img src=\"/static/images/features/pro-shop.jpg\" alt=\"Pro Shop\" class=\"w-full h-48 sm:h-64 object-cover\"></div><div class=\"rounded-2xl overflow-hidden shadow-lg\"><img src=\"/static/images/features/food.jpg\" alt=\"Restaurant and Bar\" class=\"w-full h-48 sm:h-64 object-cover\"></div></div><div class=\"text-center\"><p class=\"text-gray-600 text-lg mb-8\">Our clubhouse offers a warm, welcoming atmosphere for golfers and guests.</p><div class=\"grid md:grid-cols-3 gap-6\"><a href=\"/pro-shop\" class=\"lux-card rounded-xl p-6 card-hover block\"><h3 class=\"font-bold text-[var(--pine-green)] mb-2\">Pro Shop</h3><p class=\"text-gray-600 text-sm\">Equipment, apparel, and accessories</p></a> <a href=\"/menu\" class=\"lux-card rounded-xl p-6 card-hover block\"><h3 class=\"font-bold text-[var(--pine-green)] mb-2\">Restaurant</h3><p class=\"text-gray-600 text-sm\">Great food and drinks</p></a> <a href=\"/events\" class=\"lux-card rounded-xl p-6 card-hover block\"><h3 class=\"font-bold text-[var(--pine-green)] mb-2\">Event Space</h3><p class=\"text-gray-600 text-sm\">Host your next gathering</p></a></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(meta.New("Clubhouse", "Visit our welcoming clubhouse.")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
